CREATE DATABASE TEST;
CREATE USER 'test'@'*' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'test'@'*' WITH GRANT OPTION;
FLUSH PRIVILEGES;
USE TEST
CREATE TABLE T1 ( id INT(11) AUTO_INCREMENT, s CHAR(32), n INT(11), PRIMARY KEY (id) );
CREATE TABLE T2 ( id INT(11) AUTO_INCREMENT, s CHAR(32), PRIMARY KEY (id) );
CREATE TABLE T3 ( id1 INT(11), id2 INT(11) );
INSERT INTO T1 (s,n) VALUES ( 'test1.1',9),('test1.2',8),('test1.3',7),('test1.4',6);
INSERT INTO T2 (s) VALUES ( 'test2.1'),('test2.2'),('test2.3'),('test2.4');
INSERT INTO T3 (id1,id2) VALUES (1,3),(2,2),(3,4),(4,1);

SELECT T1.id, T1.s FROM T1;

SELECT T1.id, T1.s, T2.id, T2.s
FROM T1, T2, T3
WHERE T1.id = T3.id1
AND T3.id2 = T2.id;

DROP DATABASE TEST;
